---
- name: install java-1.7.0
  yum: name=java-1.7.0-openjdk state=installed

- name: download install src
  get_url: url=http://www.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz dest={{ tmp_dir }}

- name: unarchive src file
  unarchive: src={{ tmp_dir }}/zookeeper-3.4.6.tar.gz dest={{ home_dir }}

- name: create a data directory
  file: path={{ zookeeper_dir }}/{{ zookeeper_data }} state=directory

- name: set conf
  template: src=zoo.cfg.j2 dest={{ zookeeper_dir }}/conf/zoo.cfg

#    - name: export path
#      lineinfile: dest=/root/.bash_profile line='export PATH={{ zookeeper_dir }}/bin:$PATH'

- name: export path
  lineinfile: dest=/root/.bash_profile line='export ZOOKEEPER_HOME={{ zookeeper_dir }}'
