---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  playbook: site.yml
  hosts: localhost
  roles_path: roles
  require_ansible_repo: true

platforms:
  - name: centos-6

suites:
  - name: default
